### the core functions are defined here -------------

# Popdata_iso: combine the data downloaded from popdata with iso code, country name and UNHCR regions. Input is the raw dataset, output is a new dataset.

# ASR: download and clean the ASRdata from popdata. Input is the year, output is the dataset. This function exploits the popdata package so make sure you login with pd_login.

# MYSR: similar to ASR but for MYSR data.

# POC: function to get the total poc for aggregations at different level. The input is the raw data generated by ASR or MYSR function, the group level and year. The group level are the variables names of the raw data, recommed using 'region_d' for the regions, 'asylumCountry' for CoA or 'originCountry' for COO.

# Region_prep function to get the data disaggregated by COA or COO only belongs to the input region. The regions are simplified as Europe, Americas, Asia, EastAfrica, MENA, SouthAfrica and WestAfrica. It will also automatically save the datasets .Rdata into data-master folder, you can then load the Rdata file into the environment.


# Popdata_iso ---------------------------------------
Popdata_iso <-
  function(mydata) {
    reference <- read.csv("data-master/reference.csv")
    code <- reference %>% 
      select(iso_3, UNHCRcode, ctryname, UNHCRBureau)
    code[,] <- apply(code[,],2,as.character)
    code_o <- code %>% 
      dplyr::rename(iso_o = iso_3,
                    originCountry = ctryname,
                    region_o = UNHCRBureau)
    code_d <- code %>% 
      dplyr::rename(iso_d = iso_3,
                    asylumCountry = ctryname,
                    region_d = UNHCRBureau)
    
    mydata <- merge(mydata, code_o, by.x = "origin", by.y = "UNHCRcode", all.x = T)
    mydata <- merge(mydata, code_d, by.x = "asylum", by.y = "UNHCRcode", all.x = T)
    return(mydata)
  }


# ASR  ----------------------------------------------
ASR <- function(YEAR){
  
  ############# REFUGEE #########
  # download refugee and refugee-like table
  ref <- pd_asr(table = "refugees", year = YEAR, quiet = TRUE)
  ref_like = pd_asr(table = "refugeelike", year = YEAR, quiet = TRUE)
  
  ref$yearEndTotal <- as.numeric(ref$yearEndTotal)
  ref_like$yearEndTotal <- as.numeric(ref_like$yearEndTotal)
  
  ref$origin[ref$origin == "TIB"] <- "CHI"
  ref_like$origin[ref_like$origin == "TIB"] <- "CHI"
  
  ### concatenate the 2 tables
  concat_ref <- rbind(ref,ref_like)
  
  ### aggregate refugee figures by country of asylum and country of origin
  refugee<- concat_ref[,c('asylum','origin','yearEndTotal')] %>%
    group_by(asylum,origin) %>% 
    summarise(Refugees = sum(yearEndTotal))
  
  Refugee_reg <- ref %>% 
    group_by(asylum,origin) %>% 
    summarise(Refugee_reg = sum(yearEndTotal))
  
  Refugee_like <- ref_like %>% 
    group_by(asylum,origin) %>% 
    summarise(Refugee_like = sum(yearEndTotal))
  
  ### demo
  
  # demo = pd_asr(table = "demo", year = YEAR, quiet = TRUE)
  
  ### Asylum-seekers ###########
  
  # download rsd table
  rsd <- pd_asr(table ="rsd",year = YEAR, quiet =TRUE)
  
  # filter out UASC rows
  rsd2 <- filter(rsd, is.na(ageRange))
  
  ## aggregate rsd cases by country of asylum and country of origin
  rsdgroup <- rsd2 %>% 
    mutate(totalEndYear = as.numeric(totalEndYear))%>%
    group_by(asylum,origin) %>% summarise(RSD = sum(totalEndYear))
  
  rsdgroup$origin[rsdgroup$origin == "TIB"] <- "CHI"
  
  ### AS2 table (strategic RSD caseloads)
  as2<- pd_asr(table = "as2", year = YEAR, quiet = TRUE)
  
  ## aggregate as2 cases by country of asylum and country of origin
  as2group <- as2 %>%
    mutate(yearEndTotal = as.numeric(yearEndTotal))%>%
    group_by(asylum,origin) %>% summarise(AS2 = sum(yearEndTotal))
  
  ## merge as2 and rsd cases,
  as_rsd <- merge(as2group,rsdgroup, by=c('asylum','origin'),all=TRUE)
  
    ref$origin[ref$origin == "TIB"] <- "CHI"
  ## sum the 2 cases = number of asylum-seekers for each country of asylum and country of origin
  # new_as <- as_rsd$RSD + as_rsd$AS2
  as_rsd$Asylum_Seekers <- rowSums(as_rsd[,c("RSD","AS2")], na.rm = T)
  asy <- as_rsd[,c('asylum','origin','Asylum_Seekers')]
  
  ########## IDPs ###############
  
  # download IDP data
  idp <- pd_asr(table="idp",year=YEAR, quiet = TRUE)
  
  idpa <- idp %>% filter(type == 'IDPA') %>% 
    mutate(asylum = origin)
  idpa$totalMidYear <- as.numeric(idpa$totalMidYear)
  
  # aggregate idps by country of asylum and country of origin 
  idpgroup <- idpa[,c('asylum','origin','totalMidYear')] %>% group_by(asylum,origin) %>% summarise(IDPs = sum(totalMidYear))
  
  #### return IDPs ###########
  # from the IDP table use the field decreasesReturned for RDP population group.
  # aggregate rdp by country of asylum and country of origin
  idpa$decreasesReturned <- as.numeric(idpa$decreasesReturned)
  ridpgroup <- idpa[,c('asylum','origin','decreasesReturned')] %>% group_by(asylum,origin)%>% summarise(RIDPs = sum(decreasesReturned))
  
  ################## returnee refugee #######
  
  #download returnee table
  ret <- pd_asr(table="returnees", year = YEAR, quiet = TRUE)
  
  ## rename asylum
  # names(ret)[names(ret)=='origin'] <-"asylum"
  names(ret)[names(ret)=='asylum (from)'] <-"asylum"
  # 
  returnee <- ret %>% 
    mutate(totalReturnees = as.numeric(totalReturnees)) %>% 
    group_by(asylum, origin) %>% summarise(returns = sum(totalReturnees))
  
  
  volrep <- concat_ref[concat_ref$decreasesVoluntaryRepatriationTotal>0,]
  volrep <- volrep  %>% group_by(asylum, origin) %>% summarise(decreasesVoluntaryRepatriationTotal = sum(decreasesVoluntaryRepatriationTotal))
  
  
  allrep <- merge(returnee,volrep[,c('asylum','origin','decreasesVoluntaryRepatriationTotal')],by=c('asylum','origin'),all=TRUE)
  allrep[is.na(allrep)] = 0
  
  
  allrep$Returnee <- ifelse(allrep$returns>allrep$decreasesVoluntaryRepatriationTotal,allrep$returns,allrep$decreasesVoluntaryRepatriationTotal)
  
  ret_final <- allrep %>% select(asylum, origin, Returnee) %>% 
    mutate(asylum = origin,
           Returnee = as.numeric(Returnee)) %>% 
    group_by(asylum,origin) %>% 
    summarise(Returnee = sum(Returnee))
  
  # colnames(ret_final) <- c("origin", "asylum", "Returnee")
  
  ########## Stateless ########
  state <- pd_asr(table="stateless",year=YEAR, quiet = TRUE)
  stategroup <- state %>% group_by(asylum, origin) %>% summarise(stateless = sum(totalYearEnd))
  
  deduct <- state[(state$displacementStatus !='NDP')&(state$totalYearEnd>0),]%>%group_by(asylum,origin) %>% summarise(deduct = sum(totalYearEnd))
  
  ######## OIP##########
  
  OIP <- pd_asr(table="oip",year=YEAR, quiet = TRUE)
  
  OIP <- OIP %>% 
    mutate(totalYearEnds = as.numeric(totalYearEnd))%>% 
    group_by(asylum, origin) %>% summarise(oip = totalYearEnd)
  
  ######### Others of concern ###########
  
  ooc<- pd_asr(table="other",year=YEAR,quiet = TRUE)
  ooc$origin[ooc$origin == "TIB"] <- "CHI"
  oocgroup <- ooc %>%
    mutate(totalYearEnds = as.numeric(totalYearEnd))%>%
    group_by(asylum,origin) %>% summarise(othersOfConcern = sum(totalYearEnd))
  
  #### Combine #####
  df_list <- list(refugee,Refugee_reg, Refugee_like, asy,idpgroup,ridpgroup,ret_final,stategroup,deduct,OIP,oocgroup)
  
  master <- df_list %>% 
    reduce(full_join,by=c('asylum','origin')) %>% 
    rename(Returnee_IDP = RIDPs,
           Returnee_Refugee = Returnee,
           Stateless_Total = stateless,
           Stateless_Displaced = deduct,
           OIP = oip,
           OOC = othersOfConcern) 
  
  master2 <- Popdata_iso(master)
  master2 <- master2 %>% mutate(Year = YEAR)
  return(master2)}

# MYSR----------------------------------------------
MYSR <- function(YEAR){
  
  ############# REFUGEE #########
  # download refugee and refugee-like table
  ref <- pd_mysr(table = "refugees", year = YEAR, quiet = TRUE)
  ref_like = pd_mysr(table = "refugeeLike", year = YEAR, quiet = TRUE)
  ref$origin[ref$origin == "TIB"] <- "CHI"
  ref_like$origin[ref_like$origin == "TIB"] <- "CHI"
  
  ref$midYearTotal <- as.numeric(ref$midYearTotal)
  ref_like$midYearTotal <- as.numeric(ref_like$midYearTotal)
  
  ### concatenate the 2 tables
  concat_ref <- rbind(ref,ref_like)
  
  ### aggregate refugee figures by country of asylum and country of origin
  refugee<- concat_ref[,c('asylum','origin','midYearTotal')] %>%
    group_by(asylum,origin) %>% 
    summarise(Refugees = sum(midYearTotal))
  
  Refugee_reg <- ref %>% 
    group_by(asylum,origin) %>% 
    summarise(Refugee_reg = sum(midYearTotal))
  
  Refugee_like <- ref_like %>% 
    group_by(asylum,origin) %>% 
    summarise(Refugee_like = sum(midYearTotal))
  
  
  ### Asylum-seekers ###########
  
  # download rsd table
  rsd <- pd_mysr(table ="rsd",year = YEAR, quiet =TRUE)
  
  # filter out UASC rows
  # rsd2 <- filter(rsd, is.na(ageRange))
  
  ## aggregate rsd cases by country of asylum and country of origin
  rsdgroup <- rsd %>% 
    mutate(totalMidYear = as.numeric(totalMidYear))%>%
    group_by(asylum,origin) %>% summarise(RSD = sum(totalMidYear))
  
  rsdgroup$origin[rsdgroup$origin == "TIB"] <- "CHI"
  
  ### AS2 table (strategic RSD caseloads)
  as2<- pd_mysr(table = "as2", year = YEAR, quiet = TRUE)
  
  ## aggregate as2 cases by country of asylum and country of origin
  as2group <- as2 %>% 
    mutate(yearEndTotal = as.numeric(yearEndTotal))%>%
    group_by(asylum,origin) %>% summarise(AS2 = sum(yearEndTotal))
  
  ## merge as2 and rsd cases,
  as_rsd <- merge(as2group,rsdgroup, by=c('asylum','origin'),all=TRUE)
  
  ## fill null values with 0
  # as_rsd[is.na(as_rsd)] = 0
  
  ## sum the 2 cases = number of asylum-seekers for each country of asylum and country of origin
  # new_as <- as_rsd$RSD + as_rsd$AS2
  as_rsd$Asylum_Seekers <- rowSums(as_rsd[,c("RSD","AS2")], na.rm = T)
  asy <- as_rsd[,c('asylum','origin','Asylum_Seekers')]
  
  ########## IDPs ###############
  
  # download IDP data
  idp <- pd_mysr(table="idp",year=YEAR, quiet = TRUE)
  
  idpa <- idp %>% filter(type == 'IDPA') %>% 
    mutate(asylum = origin,
           totalMidYear = as.numeric(totalMidYear),
           decreasesReturned = as.numeric(decreasesReturned))
  
  # filter only conflict induced 
  # idpa <- idp[idp$type =='IDPA',]
  
  ## country of asylum for IDPs will be the same as its origin (adding asylum field to merge IDPs with other tables) 
  # idpa$asylum <- idpa[,c('origin')]
  
  # aggregate idps by country of asylum and country of origin 
  idpgroup <- idpa[,c('asylum','origin','totalMidYear')] %>% group_by(asylum,origin) %>% summarise(IDPs = sum(totalMidYear))
  
  #### return IDPs ###########
  # from the IDP table use the field decreasesReturned for RDP population group.
  # aggregate rdp by country of asylum and country of origin
  ridpgroup <- idpa[,c('asylum','origin','decreasesReturned')] %>% group_by(asylum,origin)%>% summarise(RIDPs = sum(decreasesReturned))
  
  ################## returnee refugee #######
  
  #download returnee table
  ret <- pd_mysr(table="returnees", year = YEAR, quiet = TRUE)
  
  ## rename asylum
  # names(ret)[names(ret)=='origin'] <-"asylum"
  names(ret)[names(ret)=='asylum (from)'] <-"asylum"
  # 
  returnee <- ret %>% 
    mutate(totalMidYear = as.numeric(totalMidYear)) %>% 
    group_by(asylum, origin) %>% summarise(returns = sum(totalMidYear))
  
  
  volrep <- concat_ref[concat_ref$decreasesVoluntaryRepatriationTotal>0,]
  volrep <- volrep  %>% group_by(asylum, origin) %>% summarise(decreasesVoluntaryRepatriationTotal = sum(decreasesVoluntaryRepatriationTotal))
  
  
  allrep <- merge(returnee,volrep[,c('asylum','origin','decreasesVoluntaryRepatriationTotal')],by=c('asylum','origin'),all=TRUE)
  allrep[is.na(allrep)] = 0
  
  
  allrep$Returnee <- ifelse(allrep$returns>allrep$decreasesVoluntaryRepatriationTotal,allrep$returns,allrep$decreasesVoluntaryRepatriationTotal)
  
  ret_final <- allrep %>% select(asylum, origin, Returnee) %>% 
    mutate(asylum = origin,
           Returnee = as.numeric(Returnee)) %>% 
    group_by(asylum,origin) %>% 
    summarise(Returnee = sum(Returnee))
  
  # colnames(ret_final) <- c("origin", "asylum", "Returnee")
  
  ########## Stateless ########
  state <- pd_mysr(table="stateless",year=YEAR, quiet = TRUE)
  stategroup <- state %>% group_by(asylum, origin) %>% summarise(stateless = sum(totalMidYear, na.rm = T))
  
  deduct <- state[(state$displacementStatus !='NDP')&(state$totalMidYear>0),]%>%group_by(asylum,origin) %>% summarise(deduct = sum(totalMidYear, na.rm = T))
  
  ######## OIP##########
  
  OIP <- pd_mysr(table="oip",year=YEAR, quiet = TRUE)

  OIP <- OIP %>% 
    mutate(totalMidYear = as.numeric(totalMidYear))%>% 
    group_by(asylum, origin) %>% summarise(oip = totalMidYear)
  
  ######### Others of concern ###########
  
  ooc<- pd_mysr(table="other",year=YEAR,quiet = TRUE)
  ooc$origin[ooc$origin == "TIB"] <- "CHI"
  oocgroup <- ooc %>% group_by(asylum,origin) %>% summarise(othersOfConcern = sum(totalMidYear))
  
  #### Combine #####
  df_list <- list(refugee,Refugee_reg, Refugee_like,asy,idpgroup,ridpgroup,ret_final,stategroup,deduct,OIP,oocgroup)
  
  master <- df_list %>% 
    reduce(full_join,by=c('asylum','origin')) %>% 
    rename(Returnee_IDP = RIDPs,
           Returnee_Refugee = Returnee,
           Stateless_Total = stateless,
           Stateless_Displaced = deduct,
           OIP = oip,
           OOC = othersOfConcern) 
  
  
  master2 <- Popdata_iso(master)
  master2 <- master2 %>% mutate(Year = YEAR)
  return(master2)}

# POC - function to get the total poc for aggregations, for region, COA or COO ----------
POC <-
  function(mydata,`mygroup`,YEAR) {
    
    groupdata <- mydata %>% group_by({{mygroup}}) 
    
    summarydata <- groupdata %>% 
      summarise(Refugees = sum(Refugees,na.rm = T),
                Refugee_reg = sum(Refugee_reg, na.rm = T),
                Refugee_like = sum(Refugee_like, na.rm = T),
                Asylum_Seekers = sum(Asylum_Seekers,na.rm = T),
                IDPs =  sum(IDPs,na.rm = T),
                Returnee_IDP =  sum(Returnee_IDP,na.rm = T),
                Returnee_Refugee =  sum(Returnee_Refugee,na.rm = T),
                Stateless_Total =  sum(Stateless_Total,na.rm = T),
                Stateless_Displaced =  sum(Stateless_Displaced,na.rm = T),
                OIP = sum(OIP, na.rm = T),
                OOC =  sum(OOC,na.rm = T)) %>% 
      mutate(Stateless_Non_displaced = Stateless_Total - Stateless_Displaced) %>% 
      mutate(POC_Total = Refugees + Asylum_Seekers + IDPs + Returnee_IDP + Returnee_Refugee + Stateless_Non_displaced + OOC + OIP,
             Forcibly_Displaced = Refugees + Asylum_Seekers + IDPs + OIP,
             Year = YEAR) %>% 
      arrange(desc(POC_Total))
    
    return(summarydata)
  }



# Refugee and refugee-like breakdown----------------------------------------------
REF_MYSR <- function(YEAR){

  ref_mysr <- pd_mysr(table = "refugees", year = YEAR, quiet = TRUE)
  ref_mysr_fil <- ref_mysr[, c("asylum", "origin","midYearTotal")]
  ref_mysr_fil <- ref_mysr_fil  %>% group_by(asylum, origin) %>% summarise(midYearTotal = sum(midYearTotal))
  colnames(ref_mysr_fil)[colnames(ref_mysr_fil) == "midYearTotal"] <- "Refugees"
  
  
  ref_like_mysr = pd_mysr(table = "refugeeLike", year = YEAR, quiet = TRUE)
  ref_like_mysr_fil <- ref_like_mysr[, c("asylum", "origin","midYearTotal")]
  ref_like_mysr_fil <- ref_like_mysr_fil  %>% group_by(asylum, origin) %>% summarise(midYearTotal = sum(midYearTotal))
  colnames(ref_like_mysr_fil)[colnames(ref_like_mysr_fil) == "midYearTotal"] <- "Refugee_like"
  
  ref_mysr_disag <- merge(ref_mysr_fil,ref_like_mysr_fil,by=c('asylum','origin'),all=TRUE)
  ref_mysr_disag[is.na(ref_mysr_disag)] <- 0
  ref_mysr_disag <- ref_mysr_disag %>% mutate("sum_ref" = ref_mysr_disag[[3]]+ref_mysr_disag[[4]])
  
  ref_mysr_disag <- ref_mysr_disag %>% mutate(origin = replace(origin, origin %in% c("HKG","MAC","TIB"),"CHI")) %>% mutate(asylum = replace(asylum, asylum %in% c("HKG","MAC","TIB"),"CHI"), Year = YEAR) 
  
  Popdata_iso(ref_mysr_disag)
}

ref_mysr2023 <- REF_MYSR(2023)

REF_ASR <- function(YEAR){
  
  ref_asr <- pd_asr(table = "refugees", year = YEAR, quiet = TRUE)
  ref_asr_fil <- ref_asr[, c("asylum", "origin","yearEndTotal")]
  ref_asr_fil <- ref_asr_fil  %>% group_by(asylum, origin) %>% summarise(yearEndTotal = sum(yearEndTotal))
  colnames(ref_asr_fil)[colnames(ref_asr_fil) == "yearEndTotal"] <- "Refugees"
  
  ref_like_asr = pd_asr(table = "refugeeLike", year = YEAR, quiet = TRUE)
  ref_like_asr_fil <- ref_like_asr[, c("asylum", "origin","yearEndTotal")]
  ref_like_asr_fil <- ref_like_asr_fil  %>% group_by(asylum, origin) %>% summarise(yearEndTotal = sum(yearEndTotal))
  colnames(ref_like_asr_fil)[colnames(ref_like_asr_fil) == "yearEndTotal"] <- "Refugee_like"
  
  ref_asr_disag <- merge(ref_asr_fil,ref_like_asr_fil,by=c('asylum','origin'),all=TRUE)
  ref_asr_disag[is.na(ref_asr_disag)] <- 0
  ref_asr_disag <- ref_asr_disag %>% mutate("sum_ref" = ref_asr_disag[[3]]+ref_asr_disag[[4]])
  
  ref_asr_disag <- ref_asr_disag %>% mutate(origin = replace(origin, origin %in% c("HKG","MAC","TIB"),"CHI")) %>% mutate(asylum = replace(asylum, asylum %in% c("HKG","MAC","TIB"),"CHI"), Year = YEAR)
  
  Popdata_iso(ref_asr_disag)
}

# Region_prep ----------------------------------
Region_prep <- function(Region, Year, Mid_End){
  
  if(Mid_End == "Mid"){
    mydata <- MYSR(Year)
  } else {
    mydata <- ASR(Year)
  }
  
  Agg_asylum <- mydata %>% filter(region_d == Region) %>% 
    arrange(asylum, origin)
  
  file_path <- file.path("data-master\\", paste0(Region,"_",Year ,"_clean_data.Rdata"))
  assign(paste0(Region, "_",Year, "_clean_data"),Agg_asylum)
  save(list = paste0(Region, "_",Year, "_clean_data"), file = file_path)
}

# Global_prep ----------------------------------
Global_prep <- function(Year, Mid_End){
  
  if(Mid_End == "Mid"){
    mydata <- MYSR(Year)
  } else {
    mydata <- ASR(Year)
  }
  
  file_path <- file.path("data-master\\", paste0("Global_",Year ,"_clean_data.Rdata"))
  assign(paste0("Global_",Year, "_clean_data"),mydata)
  save(list = paste0("Global_",Year, "_clean_data"), file = file_path)
}

# Refugee_prep ----------------------------------
Refugee_prep <- function(Year, Mid_End){
  
  if(Mid_End == "Mid"){
    mydata <- REF_MYSR(Year)
  } else {
    mydata <- REF_ASR(Year)
  }
  
  file_path <- file.path("data-master\\", paste0("Refugee_",Year,"_clean_data.Rdata"))
  assign(paste0("Refugee_",Year, "_clean_data"),mydata)
  save(list = paste0("Refugee_",Year, "_clean_data"), file = file_path)
}